spring:
  application:
    name: aha
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
  datasource:
    url: jdbc:mysql://localhost:3306/aha?timezone=Asia/Shanghai
    username: brucewu
    password: 982469065

server:
  port: 80

logging:
  file:
    name: /var/app/app.log
  logback:
    rollingpolicy:
      max-file-size: 500mb
      max-history: 30


