spring:
  application:
    name: aha
  jpa:
    open-in-view: false
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/aha?timezone=Asia/Shanghai
    username: root
    password: 982469065
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 80
  tomcat:
    threads:
      max: 400
      min-spare: 200



logging:
  file:
    name: ./logs/app.log
  logback:
    rollingpolicy:
      max-file-size: 500mb
      max-history: 30
  charset:
    console: utf-8
    file: utf-8
  level:
    root: info
    org:
      springframework:
        security: debug
    site:
      brucewu:
        aha: debug


